# Generated by Django 2.1.7 on 2019-05-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='author',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
